### ISSUE TITLE
Unable to open .trx file VS 2017/15

### ISSUE THREAD

**Issue by jonathanread** [Sitefinity/Telerik.Sitefinity.Samples.IntegrationTests#24]
After running the Telerik.WebtestRunner.Cmd version with /LoggerType="MsTrx" try and open the .trx file with with visual studio and there is an exception:

Value cannot be null.
Parameter name: id

**Additional info:**
![webtestrunner_issues](https://user-images.githubusercontent.com/3931082/46084662-30905d00-c172-11e8-9b19-c72d99fc65f7.png)

**Comment by orlindraganov** [comment]
Command line runner has been updated, trx files are now Visual Studio readable.
